apiVersion: batch/v1
kind: CronJob
metadata:
  name: complete-usertasks
spec:
  schedule: "25 10 * * *"
  successfulJobsHistoryLimit: 14
  failedJobsHistoryLimit: 14
  jobTemplate:
    metadata:
      labels: 
        app: complete-user-tasks-daily
    spec:    
      template:
        spec:
          containers:
          - name: complete-usertasks
            image: curlimages/curl:8.13.0
            imagePullPolicy: IfNotPresent
            env:
              - name: CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: payment-example-process-application-secrets
                    key: CAMUNDA_CLIENT_AUTH_CLIENTSECRET
            command:
            - /bin/sh
            - -c
            - |
              ## install jq
              apk add --no-cache jq

              I=0
              ROUNDS=22
              while [ $I -lt $ROUNDS ]; do
                echo $I
                I=$((I + 1))
                echo 'Get the token'
                TOKEN=$(curl -s --location --request POST 'http://camunda-keycloak.camunda.svc.cluster.local/auth/realms/camunda-platform/protocol/openid-connect/token' \
              --header 'Content-Type: application/x-www-form-urlencoded' \
              --data-urlencode 'client_id=payment-app' \
              --data-urlencode "client_secret=$CLIENT_SECRET" \
              --data-urlencode 'grant_type=client_credentials' | jq -r .access_token)

                echo 'Get the task list'
                IDLIST=$(curl -s -X POST \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $TOKEN" \
              -d "{\"state\":\"CREATED\",\"sort\":[{\"field\": \"creationTime\", \"order\": \"ASC\"}], \"pageSize\":200}" \
              "http://camunda-tasklist.camunda.svc.cluster.local/v1/tasks/search" | jq -r '.[].id')
              
                echo -n "Number of tasks to complete: "
                printf '%s' "$IDLIST" | jq -Rsc 'split("\n") | map(select(length>0)) | length'

                echo "Complete the tasks"
                for item in $IDLIST; do 
                  URL="http://camunda-zeebe-gateway.camunda.svc.cluster.local:8080/v2/user-tasks/${item}/completion"
                  ## echo $URL
                  curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" -d "{\"variables\": {\"errorResolved\": false}}" \
                  "${URL}" -s; 
                done
                
                if [ $I -lt $ROUNDS ]; then
                  echo "Waiting 30 s for the next round"
                  sleep 30
                fi

              done 
            securityContext:
              runAsUser: 0        
          restartPolicy: OnFailure
