server:
  port: 8083
spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: tasklist-backend
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.camunda.consulting.*"
        spring.json.use.type.headers: true
        spring.json.value.default.type: com.camunda.consulting.impl.UserTask
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tasklist
      username: demo
      password: demo
      auto-index-creation: false
      authentication-database: admin

tasklist:
  kafka:
    user-task-topic: usertask-info
    deployment-topic: deploy-info

logging:
  org:
    springframework:
      data:
        mongodb: DEBUG
