logging:
  level:
    root: info
    org:
      apache:
        http: debug
      springframework:
        security: debug
    httpclient:
      wire: debug
    com:
      okta: debug
      camunda:
        example:
          client:
            tasklist: debug
    graphql: debug
spring:
  config:
    import: application-dev.yaml
  datasource:
    url: jdbc:h2:/usr/local/opt/h2dbs/insurance-application
  jpa:
    hibernate:
      ddl-auto: update
resilience4j:
  retry:
    instances:
      operate:
        max-attempts: 15
        wait-duration: 1s