name: Build Java examples

on: [pull_request]
jobs:
  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      all_changed_files: ${{ steps.changed.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v5
      - name: Run changed-files with dir_names
        id: changed
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        with:
          dir_names: "true"
          dir_names_max_depth: '1'
          matrix: true
          files_ignore: '.github/**'
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
  build-changed-examples:
    name: Build ${{ matrix.baseDir }}
    needs: determine-changes
    if: needs.determine-changes.outputs.all_changed_files != ''
    strategy:
      fail-fast: false
      matrix:
        baseDir: ${{ fromJson(needs.determine-changes.outputs.all_changed_files) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn verify -PcheckFormat -B
        working-directory: ${{ matrix.baseDir }}

  build-payment-example-process-application:
    needs: [determine-changes,build-changed-examples]
    if: contains(needs.determine-changes.outputs.all_changed_files, 'payment-example-process-application')
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v5
    - name: Set up JDK
      uses: actions/setup-java@v5
      with: 
        java-version: '21'
        distribution: 'temurin'
#    - name: Login to Docker Hub
#      uses: docker/login-action@v3
#      with:
#        username: ${{ secrets.DOCKERHUB_USR }}
#        password: ${{ secrets.DOCKERHUB_PSW }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build with Maven
      run: mvn verify install -PcheckFormat -B
      working-directory: payment-example-process-application
    - name: Push images to ghcr.io
      run: |
        docker push -a -q ghcr.io/camunda-community-hub/camunda-8-examples/payment-example-process-application      
#    - name: Push images to dockerhub
#      run: |
#        docker push -a -q camundacommunityhub/payment-example-process-application
